# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ui0ywBqKa0oEyUlWD-rDrXXnyCS3DJut

## Calculadora
"""

## Apresentação
print("Olá, bem vindo a calculadora interativa, para começar digite seu nome: ")
nome = input("Nome: ").title()
print(f"Olá {nome}, vamos começar? Digite dois numeros inteiros e mostrarei vários calculos que podem ser realizados entre eles!")
## Armazenamento de dados e Loop de respostas
while True:
  num1 = int(input("Pirmeiro número: "))
  num2 = int(input("Segundo número: "))
  if num2 == (0): #Validação de erro
    print("Não podemos dividir por zero, encerrando a calculadora.")
    break
  print(f"O primeiro numero é {num1} e o segundo é {num2}")
  print(f"Resultado da soma entre os números: {num1 + num2}")
  print(f"Resultado da subtração entre os números: {num1 - num2}")
  print(f"Resultado da multiplicação entre os números: {num1 * num2}")
  print(f"Resultado da divisão entre os números: {num1 / num2}")
  continua = input("Deseja realizar novos calculos? (Sim/Não) ").lower()
## Encerramento ou continuação do Loop
  if continua == ("sim"):
    print(f"Boa, {nome}! Vamos continuar, insira mais dois numeros")
  elif continua == ("não"):
    print(f"Já vai? Tudo bem, até mais {nome}!")
    break
  else:
    print("Resposta invalida, encerrando a calculadora")
    break